# Generated by Django 4.2.13 on 2024-05-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0003_band_active_band_biography_band_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="listing",
            name="sold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("Records", "Records"),
                    ("Clothing", "Clothing"),
                    ("Posters", "Posters"),
                    ("Miscellaneous", "Miscellaneous"),
                ],
                default="Records",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
